# Default values for winter-soldier.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: quay.io/devtron/winter-soldier
  pullPolicy: IfNotPresent
  tag: "3f10a62b-196-5753"
resources:
  limits:
    cpu: 100m
    memory: 30Mi
  requests:
    cpu: 100m
    memory: 20Mi

hibernator_policies: 
- apiVersion: pincher.devtron.ai/v1alpha1
  kind: Hibernator
  metadata:
    name: night-time-hibernator
  spec:
    timeRangesWithZone:
      timeZone: "Asia/Kolkata"
      timeRanges:
      - timeFrom: 00:00
        timeTo: 07:59:59
        weekdayFrom: Mon
        weekdayTo: Fri
    selectors:
    - inclusions:
      - objectSelector:
          name: ""
          type: "rollout,deploy,service"
          fieldSelector:
            - AfterTime(Now(), AddTime(ParseTime({{metadata.creationTimestamp}}, '2006-01-02T15:04:05Z'), '4d'))
        namespaceSelector:
          name: "all"
    - exclusions:
      - objectSelector:
          name: ""
          type: "rollout,deployment"
        namespaceSelector:
          name: "kube-system,argo,devtroncd"
    action: sleep
- apiVersion: pincher.devtron.ai/v1alpha1
  kind: Hibernator
  metadata:
    name: non-production-hibernator
  spec:
    timeRangesWithZone:
      timeZone: "Asia/Kolkata"
      timeRanges:
      - timeFrom: 00:00
        timeTo: 23:59:59
        weekdayFrom: Mon
        weekdayTo: Sun
      - timeFrom: 00:00
        timeTo: 08:00
        weekdayFrom: Mon
        weekdayTo: Fri
      - timeFrom: 00:00
        timeTo: 23:59:59
        weekdayFrom: Mon
        weekdayTo: Fri
    selectors:
    - inclusions:
      - objectSelector:
          name: ""
          type: "rollout,deploy,service"
          fieldSelector:
            - AfterTime(Now(), AddTime(ParseTime({{metadata.creationTimestamp}}, '2006-01-02T15:04:05Z'), '4d'))
        namespaceSelector:
          name: "non-production"
      exclusions:
      - objectSelector:
          name: ""
          type: "rollout,deployment"
        namespaceSelector:
          name: "kube-system,argo,devtroncd"
    action: sleep
- apiVersion: pincher.devtron.ai/v1alpha1
  kind: Hibernator
  metadata:
    name: weekend-hibernator
  spec:
    timeRangesWithZone:
      timeZone: "Asia/Kolkata"
      timeRanges:
      - timeFrom: 00:00
        timeTo: 23:59:59
        weekdayFrom: Sat
        weekdayTo: Sun
      - timeFrom: 00:00
        timeTo: 23:59:59
        weekdayFrom: Mon
        weekdayTo: Fri
    selectors:
    - inclusions:
      - objectSelector:
          name: ""
          type: "rollout,deploy"
          fieldSelector:
            - AfterTime(Now(), AddTime(ParseTime({{metadata.creationTimestamp}}, '2006-01-02T15:04:05Z'), '4d'))
        namespaceSelector:
          name: "all"
    - exclusions:
      - objectSelector:
          name: ""
          type: "rollout,deployment"
        namespaceSelector:
          name: "kube-system,argo,devtroncd"
    action: sleep
